project_name: deps
release:
  github:
    owner: dependencies-io
    name: deps
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  - "386"
  goarm:
  - "6"
  main: ./cmd/deps
  ldflags: -s -w -X github.com/dependencies-io/deps/internal/version.version={{.Version}} -X github.com/dependencies-io/deps/internal/version.commit={{.Commit}} -X github.com/dependencies-io/deps/internal/version.date={{.Date}}
  binary: deps
  env:
  - CGO_ENABLED=0
archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - LICENSE*
  - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
